### ISSUE TITLE
Syncing does not work for miners

### ISSUE THREAD

**Issue by Luen** [cloud-at-cost/CaC-Panel-Extension#14]
The syncing payout does not work for miners.

**Comment by zack-hable** [comment]
Yes, this was on my todo to add a toggle for users to select whether they want to sync payouts as well.  If you can give this [build](https://github.com/cloud-at-cost/CaC-Panel-Extension/releases/tag/v0.1.16) a try first, it'd be greatly appreciated (as I don't have any payouts on my transaction log to test against).

**Comment by Luen** [comment]
Yes, the new build works. Thanks

**Comment by Luen** [comment]
It seems to have an issue with syncing every transaction though. It only syncs the transaction for the XCH80 miner, and not the others (X80 & X80a).

**Comment by zack-hable** [comment]
Have you added both miners to the CloudAtCocks Analytics site?

**Comment by Luen** [comment]
Yes, it seems to be logging all the transactions regardless of miner id to the last miner that was added to the CloudAtCocks panel.

After clicking 'Reset and Reload All Transactions', the plugin says "Successfully forwarded 889 new transactions to panel (found 1700 total)" 

![image](https://user-images.githubusercontent.com/1161837/130305448-07aea57e-e73b-4355-a40d-a974cdc25fec.png)
![image](https://user-images.githubusercontent.com/1161837/130305461-551b87b8-5cdd-492b-98fb-640e093b9eab.png)
![image](https://user-images.githubusercontent.com/1161837/130305486-fa53cef5-2855-41a0-b9ed-bfaa8b09d3c0.png)

**Comment by zack-hable** [comment]
I think this may be due to a DOM change on the C@C Wallet site.  I'm building [0.1.17](https://github.com/cloud-at-cost/CaC-Panel-Extension/releases/tag/v0.1.17) if you can give that a test.  Thanks again for helping me out!

**Comment by Luen** [comment]
I've updated the plugin and it's still logging the transactions under the same miner - the last one that was added (18573 M1a Miner).


https://wallet.cloudatcost.com/
![image](https://user-images.githubusercontent.com/1161837/130310422-f7c6a686-1b21-4564-bb52-24035d33c2a5.png)

https://wallet.cloudatcost.com/miner
![image](https://user-images.githubusercontent.com/1161837/130310435-cc842f03-7800-4408-ab17-89b1afdf594d.png)

**Comment by zack-hable** [comment]
I'm not sure what the issue is here.  My unit tests pass for parsing a mock transaction page and miner page.  Are you able to send me a copy of your HTML of these pages: https://wallet.cloudatcost.com/miner and https://wallet.cloudatcost.com/transaction so I can test locally?  If you're a part of our discord, I'm available there as Zack (BattleShiba#8859) if you'd like to DM it.

**Comment by zack-hable** [comment]
I've worked with @awjudd and we've identified the issue being that an old field (packageID) was causing the issue here and have removed it.  If you're willing to give this [build](https://github.com/cloud-at-cost/CaC-Panel-Extension/releases/tag/v0.1.17-rc.0) a try it would be appreciated.  It did appear to work on my end.

**Comment by Luen** [comment]
It seems to work a little better now but still has issues with syncing everything on the CloudAtCocks panel - only seems to be logging the payouts for the XCH80 (chia) and the M1a Miner (free). In the panel is shows X80, XCH80, M1a, but not for the X80a and in the miner URL, it only shows the XCH80 and M1a. See screenshots below. 

![image](https://user-images.githubusercontent.com/1161837/130595882-fbc122f2-4fc0-404b-843c-0c382623dab9.png)
![image](https://user-images.githubusercontent.com/1161837/130596032-4e1c93eb-03f4-4aac-8ba7-998e32cfb939.png)
![image](https://user-images.githubusercontent.com/1161837/130596136-638eee39-8c95-4505-b37f-c245a2df1338.png)


I've sent you a discord message with the HTML of both pages.

**Comment by zack-hable** [comment]
I've got your message and I think I see the issue here.  If you purchased the X80 and X80a on the old panel then their miner id field has changed in the new panel.  I believe from the files you've sent this is the case (I'll send a separate PM there with more specific details to preserve the privacy of your miner IDs)

**Comment by Luen** [comment]
Thank you @zack-hable & @awjudd 
I've just updated the Miner ID in the cloudatcocks panel and it works well. 
Cheers
